# TCL File Generated by Component Editor 18.1
# Fri May 02 15:17:35 CEST 2025
# DO NOT MODIFY


# 
# led_matrix_driver "led_matrix_driver" v1.0
#  2025.05.02.15:17:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_matrix_driver
# 
set_module_property DESCRIPTION ""
set_module_property NAME led_matrix_driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME led_matrix_driver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_matrix_driver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_matrix_driver.v VERILOG PATH ../led_matrix_driver.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ENABLE_DEFAULT INTEGER 1 ""
set_parameter_property ENABLE_DEFAULT DEFAULT_VALUE 1
set_parameter_property ENABLE_DEFAULT DISPLAY_NAME ENABLE_DEFAULT
set_parameter_property ENABLE_DEFAULT WIDTH ""
set_parameter_property ENABLE_DEFAULT TYPE INTEGER
set_parameter_property ENABLE_DEFAULT UNITS None
set_parameter_property ENABLE_DEFAULT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_DEFAULT DESCRIPTION ""
set_parameter_property ENABLE_DEFAULT HDL_PARAMETER true
add_parameter RESET_DEFAULT INTEGER 0 ""
set_parameter_property RESET_DEFAULT DEFAULT_VALUE 0
set_parameter_property RESET_DEFAULT DISPLAY_NAME RESET_DEFAULT
set_parameter_property RESET_DEFAULT WIDTH ""
set_parameter_property RESET_DEFAULT TYPE INTEGER
set_parameter_property RESET_DEFAULT UNITS None
set_parameter_property RESET_DEFAULT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RESET_DEFAULT DESCRIPTION ""
set_parameter_property RESET_DEFAULT HDL_PARAMETER true
add_parameter MAT_WIDTH INTEGER 64 ""
set_parameter_property MAT_WIDTH DEFAULT_VALUE 64
set_parameter_property MAT_WIDTH DISPLAY_NAME MAT_WIDTH
set_parameter_property MAT_WIDTH WIDTH ""
set_parameter_property MAT_WIDTH TYPE INTEGER
set_parameter_property MAT_WIDTH UNITS None
set_parameter_property MAT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAT_WIDTH DESCRIPTION ""
set_parameter_property MAT_WIDTH HDL_PARAMETER true
add_parameter MAT_HEIGHT INTEGER 32 ""
set_parameter_property MAT_HEIGHT DEFAULT_VALUE 32
set_parameter_property MAT_HEIGHT DISPLAY_NAME MAT_HEIGHT
set_parameter_property MAT_HEIGHT WIDTH ""
set_parameter_property MAT_HEIGHT TYPE INTEGER
set_parameter_property MAT_HEIGHT UNITS None
set_parameter_property MAT_HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAT_HEIGHT DESCRIPTION ""
set_parameter_property MAT_HEIGHT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_in
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 read read Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_in
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 16
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink ready ready Output 1
add_interface_port avalon_streaming_sink valid valid Input 1
add_interface_port avalon_streaming_sink data data Input 16
add_interface_port avalon_streaming_sink startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink endofpacket endofpacket Input 1


# 
# connection point clock_out
# 
add_interface clock_out clock start
set_interface_property clock_out associatedDirectClock ""
set_interface_property clock_out clockRate 0
set_interface_property clock_out clockRateKnown false
set_interface_property clock_out ENABLED true
set_interface_property clock_out EXPORT_OF ""
set_interface_property clock_out PORT_NAME_MAP ""
set_interface_property clock_out CMSIS_SVD_VARIABLES ""
set_interface_property clock_out SVD_ADDRESS_GROUP ""

add_interface_port clock_out CLK clk Output 1


# 
# connection point clock_in
# 
add_interface clock_in clock end
set_interface_property clock_in clockRate 0
set_interface_property clock_in ENABLED true
set_interface_property clock_in EXPORT_OF ""
set_interface_property clock_in PORT_NAME_MAP ""
set_interface_property clock_in CMSIS_SVD_VARIABLES ""
set_interface_property clock_in SVD_ADDRESS_GROUP ""

add_interface_port clock_in clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_in
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset areset_n reset_n Input 1


# 
# connection point conduit_out
# 
add_interface conduit_out conduit end
set_interface_property conduit_out associatedClock ""
set_interface_property conduit_out associatedReset ""
set_interface_property conduit_out ENABLED true
set_interface_property conduit_out EXPORT_OF ""
set_interface_property conduit_out PORT_NAME_MAP ""
set_interface_property conduit_out CMSIS_SVD_VARIABLES ""
set_interface_property conduit_out SVD_ADDRESS_GROUP ""

add_interface_port conduit_out A row_sel_a Output 1
add_interface_port conduit_out B row_sel_b Output 1
add_interface_port conduit_out B1 blue_1 Output 1
add_interface_port conduit_out B2 blue_2 Output 1
add_interface_port conduit_out C row_sel_c Output 1
add_interface_port conduit_out D row_sel_d Output 1
add_interface_port conduit_out G1 green_1 Output 1
add_interface_port conduit_out G2 green_2 Output 1
add_interface_port conduit_out LAT latch Output 1
add_interface_port conduit_out OE_n output_en Output 1
add_interface_port conduit_out R1 red_1 Output 1
add_interface_port conduit_out R2 red_2 Output 1

